FROM node:24-alpine

WORKDIR /app
RUN apk add --no-cache bash

COPY package*.json ./

RUN npm install && npm install -g @nestjs/cli

COPY . .

ENV NODE_ENV=development

EXPOSE 5000

CMD ["npm", "run", "start:dev"]
